export * from './types'
export {
  testImapConnection,
  connectImap,
  forceDisconnectImap,
  listMailboxes,
  fetchInboxSummaries,
  fetchFolderSummariesPage,
  fetchAllFolderHeaders,
  syncFolderFlagsOnly,
  getMailboxMessageCount,
  getMailboxStatus,
  setSeen,
  setFlagged,
  startIdle,
  stopIdle,
  saveDraft,
  deleteDraft,
  withSaveDraftLock,
  sweepOrphanDrafts,
  moveMessages,
  deleteMessagesRemote,
  detectFolderRoles,
  appendToMailbox,
  createMailbox,
  renameMailbox,
  deleteMailbox,
  disconnectAllPerAccount,
  disconnectPerAccount,
  isIdleActive,
  imapSearchFolder,
  fetchSummariesByUids,
} from './imap'
export { testSmtpConnection, sendMail, buildRawMessage, classifySmtpError, SMTP_RETRY_DELAYS_MS } from './smtp'
export {
  listAccounts,
  getAccountMeta,
  getAccountConfig,
  getOauthRefreshToken,
  getOauthRefreshTokenWithSource,
  setOauthRefreshToken,
  deleteLegacyGoogleRefreshToken,
  lookupOauthRefreshToken,
  lookupOauthRefreshTokenWithSource,
  oauthRefreshSecretKey,
  legacyGoogleRefreshSecretKey,
  saveAccount,
  deleteAccount,
  listMcpConnections,
  getMcpConnection,
  saveMcpConnection,
  deleteMcpConnection,
  accountSchema,
  accountSaveSchema,
  imapSchema,
  smtpSchema,
  folderRolesSchema,
  mcpConnectionSchema,
  mcpConnectionObjectSchema,
  mcpSaveConnectionSchema,
  mcpSaveConnectionObjectSchema,
  settingsSchema,
  rendererWritableSettingsSchema,
  MAIN_ONLY_SETTINGS_FIELDS,
  BODY_RETENTION_DAYS_VALUES,
  DEFAULT_BODY_RETENTION_DAYS,
  DEFAULT_MCP_STDIO_COMMAND_ALLOWLIST,
  isAllowedMcpStdioCommand,
  FORBIDDEN_MCP_STDIO_ENV_KEYS,
  isForbiddenMcpStdioEnvKey,
  findForbiddenMcpStdioEnvKeys,
  sanitizeMcpConnectionsEnv,
  setMcpEnvSanitizationListener,
  getSettings,
  saveSettings,
} from './config'
export type { RendererWritableSettings, MainOnlySettingsField, SanitizeMcpConnectionsEnvResult, McpEnvSanitizationListener } from './config'
export { fetchMessageDetails, fetchMessageBody, fetchMessageBodyViaMain, downloadMessagePart, downloadRawMessage, downloadRawMessagePerAccount } from './message'
export {
  parseEmlBuffer,
  parseEmlBufferInline,
  extractEmlAttachment,
  EML_ATTACHMENT_PART_PREFIX,
} from './eml'
export { EML_WORKER_MIN_BYTES } from './emlWorkerClient'
export { saveEml, readEml, emlExists, deleteEml, deleteEmls, deleteAccountEmls, emlCacheSizeBytes } from './mailStore'
export { autoconfig } from './autoconfig'
export { normalizeFingerprintSha256, buildTlsOptions } from './tls'
export { tryAutoUnsubscribe, tryRfc8058Post, tryHttpGetUnsubscribe, pickHttpsUrl, extractUnsubLinksFromHtml } from './unsubscribe'
export type { HttpUnsubscribeResult } from './unsubscribe'
